language: csharp
solution: Source/SharpAESCrypt.sln
install:
  - msbuild Source/SharpAESCrypt.sln /t:Restore
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Source/SharpAESCrypt.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Unittest/bin/Release/Unittest.dll -exclude:Bulk
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Unittest/bin/Release/Unittest.dll -include:Bulk
