language: csharp
solution: Source/SharpAESCrypt.sln
install:
  - nuget restore Source/SharpAESCrypt.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Source/SharpAESCrypt.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Unittest/bin/Release/Unittest.dll /exclude:Bulk
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Unittest/bin/Release/Unittest.dll /include:Bulk